-- a = "b" is the same as "Naughty player you cant build a till youve built b!"
-- XTA 2007
local buildRestrictionDefs = {
    aven_fusion_reactor={"aven_cloakable_fusion_reactor"},
--  gear_cloakable_fusion_power_plant={"gear_light_fusion_power_plant"},
    gear_fusion_power_plant={"gear_cloakable_fusion_power_plant"},
    
    aven_adv_aircraft_plant={"aven_kbot_lab",
                      "aven_light_plant",
                      "aven_aircraft_plant",
                      "aven_hovercraft_platform",
                      "aven_seaplane_platform",
                      "aven_shipyard"},
    aven_adv_kbot_lab={"aven_kbot_lab",
                      "aven_light_plant",
                      "aven_aircraft_plant",
                      "aven_hovercraft_platform",
                      "aven_seaplane_platform",
                      "aven_shipyard"},
    aven_adv_shipyard={"aven_kbot_lab",
                      "aven_light_plant",
                      "aven_aircraft_plant",
                      "aven_hovercraft_platform",
                      "aven_seaplane_platform",
                      "aven_shipyard"},
    aven_adv_vehicle_plant={"aven_kbot_lab",
                      "aven_light_plant",
                      "aven_aircraft_plant",
                      "aven_hovercraft_platform",
                      "aven_seaplane_platform",
                      "aven_shipyard"},


-- core factories
    gear_adv_aircraft_plant={"gear_kbot_lab",
                      "gear_light_plant",
                      "gear_aircraft_plant",
                      "gear_hovercraft_platform",
                      "gear_seaplane_platform",
                      "gear_shipyard"},
    gear_adv_kbot_lab={"gear_kbot_lab",
                      "gear_light_plant",
                      "gear_aircraft_plant",
                      "gear_hovercraft_platform",
                      "gear_seaplane_platform",
                      "gear_shipyard"},
    gear_adv_shipyard={"gear_kbot_lab",
                      "gear_light_plant",
                      "gear_aircraft_plant",
                      "gear_hovercraft_platform",
                      "gear_seaplane_platform",
                      "gear_shipyard"},
    gear_adv_vehicle_plant={"gear_kbot_lab",
                      "gear_light_plant",
                      "gear_aircraft_plant",
                      "gear_hovercraft_platform",
                      "gear_seaplane_platform",
                      "gear_shipyard"},
                      
    gear_krogoth_gantry={
                      "gear_adv_aircraft_plant",
                      "gear_adv_kbot_lab",
                      "gear_adv_shipyard",
                      "gear_adv_vehicle_plant"},
}
return buildRestrictionDefs